### ISSUE TITLE
Concurrent write error

### ISSUE THREAD

**Issue by bjartek** [onflow/flow#38] opened 2020-08-23 10:20 UTC
## Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem
A concurrent write error occured when starting up a react app

Relevant github repos: 
Contracts: https://github.com/versus-flow/auction-flow-contract/tree/concurrent_write
React app: https://github.com/versus-flow/versus-action-website/tree/concurrent-write

### Steps to Reproduce 

1. in terminal 1 Clone  https://github.com/versus-flow/auction-flow-contract/tree/concurrent_write and cd into that folder
2. In terminal 1 start the flow emulator in that repo `flow emulator start -v`
3. In terminal 2 run `make webpage`
4. In terminal 3 Clone https://github.com/versus-flow/versus-action-website/tree/concurrent-write and cd into die
5. In terminal 3 run `yarn run dev-wallet
6. In terminal 4 run `yarn start` in te website repo
7. Sign in with a user in the dev-wallet.
8. Stop emulator, dev-wallet
9. Keep session in webbrowser open
10. start emulator, run `make webpage`, start dev-wallet and start the webapp again
11. refresh the webpage.

flow version:
Version: v0.9.0
Commit: a286d775fc3e38ca2fd9eb58a8275bb6e2067e14

See gist https://gist.github.com/bjartek/37088a4339e888bfbec2417858717b9b for the stack trace

**Comment by turbolent** [comment] 2020-08-24 18:53
@bjartek Thank you for the detailed bug report, this is great! Looking at the stack trace, it looks like there's a concurrent access in the emulator. I'll see if I can write a test case for it that can reproduce it and then fix it

**Comment by turbolent** [comment] 2020-08-24 19:53
I think, but am not sure, that the problem is that `MapLedger.Get` is writing to `RegisterTouches`, and callers of `MapLedger.Get`, which seems to be only `Store.LedgerViewByHeight`, acquires only read lock  – but as a write occurs, I think it should be a write lock.

Also, maybe `MapLedger` itself should have a lock which handles this properly, so that users of `MapLedger` don't have to worry about the implementation details (i.e., reading also has a write side-effect)

**Comment by turbolent** [comment] 2020-08-24 21:38
Fix is merged, this will be in the next release

**Closed** 2020-08-24 21:37 UTC
Labels: Feedback, bug

**Comment by bjartek** [comment] 2020-08-25 08:00
👍
